name: API Platform Workflow

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: |
        cd backend/api && composer install --no-scripts --no-interaction

    - name: Run Tests
      run: |
        cd backend/api && bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: |
        cd backend/api && composer install --optimize-autoloader --no-scripts --no-interaction

    - name: Set up API Platform
      run: |
        cd backend/api && bin/console doctrine:schema:create
        cd backend/api && bin/console hautelook:fixtures:load --no-interaction

    - name: Deploy to Production
      run: |
        # Example: scp -r ./your-app/* user@your-server:/path/to/your/app