name: API Platform Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: |
          cd backend/api && composer install --no-scripts --no-interaction

      - name: Run Tests
        run: |
          cd backend/api && bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env.local File
        env:
          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
          MAILER_DSN: ${{ secrets.MAILER_DSN }}
          WEBSITE_URI: ${{ secrets.WEBSITE_URI }}
        run: |
          envsubst < backend/api/.env.local.template > backend/api/.env.local

      - name: Add SSH Key to Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push PHP Docker Image
        run: |
          docker build -t twiney/app-php:latest -f ./backend/api/Dockerfile ./backend/api
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push twiney/app-php:latest

      
      - name: Deploy with Docker
        env:
          SERVER_SSH: ${{ secrets.SERVER_SSH }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |   
          # Copy the Docker Compose file to the server
          scp ./backend/compose.prod.yaml ${{ env.SERVER_SSH }}:${{ env.SERVER_PATH }}/compose.yaml
          # Run docker-compose on the server using the compose file
          ssh ${{ env.SERVER_SSH }} 'cd ${{ env.SERVER_PATH }} && docker-compose -f compose.yaml up -d --build'
      
